# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_push_image
  displayName: Build & push image
  jobs:  
  - job: Build_push_image
    displayName: Build & push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        echo $(BUILD_SOURCEVERSION)
        export GIT_HASH=$(BUILD_SOURCEVERSION)
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: dockerhub-service
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: dockerhub-service
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: iradu/varnish4
        tags: |
          azure
          $(GIT_HASH)
